# Generated by Django 6.0.4 on 2026-04-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hamjamiyat',
                'verbose_name_plural': 'Hamjamiyatlar',
                'db_table': 'communities',
            },
        ),
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=150)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_messages', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.community')),
            ],
            options={
                'verbose_name': 'Hamjamiyat xabari',
                'verbose_name_plural': 'Hamjamiyat xabarlari',
                'db_table': 'community_messages',
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Ega'), ('member', "Hamjamiyat a'zosi")], db_index=True, default='member', max_length=15)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Hamjamiyat a'zosi",
                'verbose_name_plural': "Hamjamiyat a'zolari",
                'db_table': 'community_members',
                'constraints': [models.UniqueConstraint(fields=('user', 'community'), name='unique_user_community')],
            },
        ),
    ]
