# Generated by Django 6.0.4 on 2026-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_profile',
            field=models.ImageField(blank=True, null=True, upload_to='community/%Y/%m/%d/'),
        ),
    ]
