# Generated by Django 6.0.4 on 2026-04-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('new_post', 'Yangi post'), ('community_messages', 'Hamjamiyatdan xabar')], max_length=35)),
                ('message', models.TextField(max_length=300)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notifications',
            },
        ),
    ]
